### ISSUE TITLE
mj_loadXML error: b"Error: could not open STL file

### ISSUE THREAD

**Issue by SangbaekYoo** [tudorjnu/cathsim#1]
I try to run cathsim.(just run python3 tests/test_env.py) There are some issues. 
First, scene.xml file (in cathsim/cathsim_env/envs/) includes catheter.xml, but there is cathter_template.xml in this directory, I don't understand why this file names are different. 

Second, there are no walls.stl file. scene directory should be in meshes directory but there are only phantom_1, phantom_2 and slave. How can I solve this problem?

**Comment by tudorjnu** [comment]
Hello @SangbaekYoo! 

Indeed, I tried to re-run it and it seemed to throw an error. I have investigated it and now it should be fixed. 

Let me know if it is fixed for you or if there is any other issue.

**Comment by SangbaekYoo** [comment]
> 
Thank you for response my question. Now I can run basic example. I also want to render simulation with obs_type 'image', but there is some error. Is there need anothor modification in code? My current code is below.

import cathsim_env
import gym


env = gym.make('cathsim_env/CathSim-v0', 
                scene=1,  # 1 or 2 for Type-I Aortic Arch and Type-II Aortic Arch 
                target="bca",  # "bca" or "lcca"
                obs_type="image", # image or internal
                image_size=128, 
                delta=0.008, # the distance threshold between catheter head and target
                success_reward=10.0, # the reward for reaching the target
                compute_force=False, # whether to compute the force
                dense_reward=True, # whether to use a dense reward or a sparse reward,
                )

obs = env.reset()
for _ in range(2000):
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    env.render()

**Comment by tudorjnu** [comment]
Ahh, this is a more complicated issue that has to do with glfw see [issue 2989](https://github.com/openai/gym/issues/2989) on openai/gym. 

However, as a wrap-around, you can try to the cv2 images by rendering the single frames.

**Comment by tudorjnu** [comment]
I am closing this issue. Please let me know if there are more issues.
