### ISSUE TITLE
Keyboard Input

### ISSUE THREAD

**Issue by vovantuan1999a** [tudorjnu/cathsim#2]
Dear Sir,

My name is Tuan Vo Van.
 
I was hoping you could provide me with some guidance on setting up the environment and controlling the catheter's dynamics by keyboards in the Aorta using the Mujoco environment.

Thank you for taking the time to consider my request. I look forward to hearing back from you.

Best regards,
Tuan Vo Van

**Comment by tudorjnu** [comment]
Hello Tuan!

You can have a look at the custom `launch` function from [here](https://github.com/tudorjnu/cathsim/blob/e6b234f587c8318cdaf52ba9ad6bfa377eaa1a26/cathsim/utils.py#LL173C5-L173C11). You can take out the saving of time steps and just keep the basic callbacks. I will push an updated version that contains that functionality as a command. Let me know how it goes.

**Comment by vovantuan1999a** [comment]
Thank you for your support. 
I will definitely take a look at it and try to implement it as per your suggestion. I will also take out the saving of time steps and keep the basic callbacks.

I am looking forward to the updated version that contains the functionality as a command. I will definitely let you know how it goes once I have tried implementing it.

Thanks again for your support.
