### ISSUE TITLE
MuJoCo compatibility

### ISSUE THREAD

**Issue by csudiptach** [tudorjnu/cathsim#5]
Hi Tudor,

Apologies this might be silly issue being raised
I am having some difficulty trying to run the Quickstart on VSCode on my personal mac(M1). Been having some issues with this error for a while, I tried online searches to fix it but failing in it even though I have installed arm64. Do you know how to fix it please to proceed?

ImportError: You are running an x86_64 build of Python on an Apple Silicon machine. This is not supported by MuJoCo. Please install and run a native, arm64 build of Python.

**Comment by tudorjnu** [comment]
I think this issue is best checked with MuJoCo itself - [here](https://github.com/deepmind/mujoco).
